/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.bindery

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main() {
    val largePrimes = Prime.getSetOfPrimesInRange(1..Long.MAX_VALUE)

    println(largePrimes)
}
