/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.bindery

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val max = 100000L
    val largePrimes = Prime.getSetOfPrimesInRange(1..max)

    println(largePrimes)
}
